spring:
  cloud:
    gateway:
      routes:
        - id: john_yml
          uri: http://httpbin.org
          predicates:
            - Path=/get
      discovery:
        locator:
          enabled: true
  application:
    name: gateway
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

logging:
  level:
    org.springframework.cloud.gateway: debug