spring:
  cloud:
    gateway:
      routes:
        - id: john_yml
          #uri: http://httpbin.org
          uri: lb://myprovider
          filters:
            - AddRequestParameter=name,john
          predicates:
            #- Query=name,john.*
            #- After=2021-01-01T01:01:01+08:00[Asia/Shanghai]
            - Method=GET
            #- Path=/binorg
  application:
    name: gateway
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

logging:
  level:
    org.springframework.cloud.gateway: debug